input {
  heartbeat {
    interval => 10
    message => "elkwatch-dev-heartbeat"
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "heartbeat-%{+YYYY.MM.dd}"
  }
}